name: planets_webs
description: Planets web application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  injectable: ^2.4.4
  get_it: ^7.7.0
  http: ^1.2.2
  dartz: ^0.10.1
  image_network: ^2.5.6
  
  #Package Global
  planets_ui: 0.1.0+1
  planets_data: 0.1.0+1
  go_router: ^14.2.8
  shared_preferences: ^2.3.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/